### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by blakelucas** [blakelucas/STT3850-Group-Project#1]
- [ ] hypothesis?
- [ ] plot heatmap of csv
- [ ] compare utility rates by zip and geography
- [ ] compare utility rates to tax rates by state
- [ ] powerpoint
- [ ] 3 page write up

**Comment by blakelucas** [comment]
- [ ] do this thing

**Comment by BrendanDavisASU** [comment]
comm_rate - Commercial rates
ind_rate - Industrial rates
res_rate - Residential Rates
All are in units of $/ kwh and are average rate per utility (AKA not including complex pay structures)

**Comment by BrendanDavisASU** [comment]
All Money Data is in thousands of dollars
Important data from second chart
STATE
ZIPCODE - zip
A18300 - Total taxes paid
A00100 - Adjusted Gross Income
N2 - number of individuals
SCHF - number of farm returns
A03220 - educator returns amount
